# Generated by Django 4.2.20 on 2025-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('purple', 'Purple'), ('white', 'White'), ('gray', 'Gray'), ('rainbow', 'Rainbow')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='product.color'),
        ),
    ]
