# Generated by Django 4.2.20 on 2025-07-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productgroup_product_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_color', to='product.color'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('light_blue', 'Light Blue'), ('white', 'White'), ('gray', 'Gray'), ('rainbow', 'Rainbow')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='products_available_colors', to='product.color'),
        ),
        migrations.DeleteModel(
            name='ProductColorImage',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
