# Generated by Django 4.2.20 on 2025-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_product_group_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('pink', 'Pink'), ('light_pink', 'Light Pink'), ('rose_red', 'Rose Red'), ('red', 'Red'), ('yellow', 'Yellow'), ('light_yellow', 'Light Yellow'), ('orange', 'Orange'), ('gold_black', 'Gold & Black'), ('yellow_black', 'Yellow & Black'), ('green', 'Green'), ('dark_green', 'Dark Green'), ('seafoam', 'Seafoam'), ('seafoam_blue', 'Seafoam Blue'), ('teal', 'Teal'), ('blue', 'Blue'), ('light_blue', 'Light Blue'), ('dark_blue', 'Dark Blue'), ('medium_blue', 'Medium Blue'), ('purple', 'Purple'), ('grape', 'Grape'), ('gray', 'Gray'), ('light_grey', 'Light Grey'), ('dark_grey', 'Dark Grey'), ('black', 'Black'), ('white', 'White'), ('peach', 'Peach'), ('mixed', 'Mixed'), ('rainbow', 'Rainbow')], max_length=20, unique=True),
        ),
    ]
