# Generated by Django 5.2.3 on 2025-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care_details',
        ),
    ]
